apiVersion: apps/v1
kind: Deployment
metadata:
  name: shifutask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shifutask
  template:
    metadata:
      labels:
        app: shifutask
    spec:
      containers:
        - name: shifutask
          image: shifutask:latest
