apiVersion: apps/v1
kind: Deployment
metadata:
  name: aatest-shifu
build:
  local:
    push: false
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aatest-shifu
  template:
    metadata:
      labels:
        app: aatest-shifu
    spec:
      containers:
        - name: shifutask
          image: shifutask
